---
name: isotovideo - github action example
# yamllint disable-line rule:truthy
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: "registry.opensuse.org/devel/openqa/containers/isotovideo:qemu-x86-jq"
    steps:
      - uses: actions/checkout@v4

      - name: Run isotovideo against test code
        run: isotovideo --exit-status-from-test-results qemu_no_kvm=1 casedir=.
